openapi: 3.0.0
info:
  title: Wine Image API
  version: 1.0.0
paths:
  /image:
    get:
      summary: Get an image of a new wine
      operationId: getImage
      responses:
        '200':
          description: OK
          content:
            image/jpeg: {}  